# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigForm\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 455)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fieldList = QtWidgets.QListWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldList.sizePolicy().hasHeightForWidth())
        self.fieldList.setSizePolicy(sizePolicy)
        self.fieldList.setMinimumSize(QtCore.QSize(50, 60))
        self.fieldList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.fieldList.setObjectName("fieldList")
        self.horizontalLayout.addWidget(self.fieldList)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.AddDeadlineButton = QtWidgets.QPushButton(Dialog)
        self.AddDeadlineButton.setObjectName("AddDeadlineButton")
        self.verticalLayout_3.addWidget(self.AddDeadlineButton)
        self.EditDeadlineButton = QtWidgets.QPushButton(Dialog)
        self.EditDeadlineButton.setObjectName("EditDeadlineButton")
        self.verticalLayout_3.addWidget(self.EditDeadlineButton)
        self.DeleteDeadlineButton = QtWidgets.QPushButton(Dialog)
        self.DeleteDeadlineButton.setObjectName("DeleteDeadlineButton")
        self.verticalLayout_3.addWidget(self.DeleteDeadlineButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.OneOrManyLabel = QtWidgets.QLabel(Dialog)
        self.OneOrManyLabel.setObjectName("OneOrManyLabel")
        self.horizontalLayout_3.addWidget(self.OneOrManyLabel)
        self.OneOrManyBox = QtWidgets.QComboBox(Dialog)
        self.OneOrManyBox.setObjectName("OneOrManyBox")
        self.OneOrManyBox.addItem("")
        self.OneOrManyBox.addItem("")
        self.horizontalLayout_3.addWidget(self.OneOrManyBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ProcessDeadlineBox = QtWidgets.QPushButton(Dialog)
        self.ProcessDeadlineBox.setObjectName("ProcessDeadlineBox")
        self.horizontalLayout_4.addWidget(self.ProcessDeadlineBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.fieldList, self.AddDeadlineButton)
        Dialog.setTabOrder(self.AddDeadlineButton, self.DeleteDeadlineButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "editing_fields"))
        self.AddDeadlineButton.setText(_translate("Dialog", "Add Deadline"))
        self.EditDeadlineButton.setText(_translate("Dialog", "Edit Deadline"))
        self.DeleteDeadlineButton.setText(_translate("Dialog", "Delete Deadline"))
        self.OneOrManyLabel.setText(_translate("Dialog", "Choose Pop-Up Style"))
        self.OneOrManyBox.setItemText(0, _translate("Dialog", "Single Summary Pop Up"))
        self.OneOrManyBox.setItemText(1, _translate("Dialog", "One Pop Up per Deck"))
        self.ProcessDeadlineBox.setText(_translate("Dialog", "Process Deadlines"))
